In [4]:
# Let's load the dataset:
import pandas as pd

df = pd.read_csv("furniture.csv")
df.head()

,brand,category,material,delivery_days,inventory,cost,discount_percentage,price
0,Furneyz,Bed,Plastic,9,105,181.61,27.8,273.18
1,Krude,Chair,Glass,6,192,385.03,26.9,477.82
2,Krude,Table,Metal,2,59,276.74,21.9,379.40
3,Krude,Table,Glass,2,45,281.84,11.0,319.40
4,Krude,Chair,Glass,9,35,69.74,3.2,120.21

In [6]:
# Let's inspect duplicate rows:
duplicate_count = df.duplicated().sum()
duplicate_count

# The amount of duplicate rows is 110

np.int64(110)

In [7]:
# Let's remove the duplicate rows:
df = df.drop_duplicates()

In [20]:
# Now we inspect the NaN values:
# Since I didn't know how to do this I asked CoPilot for help. 
# This is the following result:
nan_count = df.isna().sum()
nan_count

brand                    0
category                 0
material                 0
inventory                0
cost                     0
discount_percentage      0
price                  197
delivery_category        0
dtype: int64

In [9]:
# Now we remove all rows that contain these values
df_clean = df.dropna()

In [14]:
# Let's create a new column:
def categorize_delivery(days):
    if days < 4:
        return "quick"
    elif 4 <= days <= 7:
        return "normal"
    else:
        return "slow"

#Let's apply this to the dataset:
df["delivery_category"] = df["delivery_days"].apply(categorize_delivery)

# Let's inspect:
df["delivery_category"].value_counts()

delivery_category
normal    1124
quick      858
slow       516
Name: count, dtype: int64

In [15]:
# Lets preview now the dataset:
df.head()

,brand,category,material,delivery_days,inventory,cost,discount_percentage,price,delivery_category
0,Furneyz,Bed,Plastic,9,105,181.61,27.8,273.18,slow
1,Krude,Chair,Glass,6,192,385.03,26.9,477.82,normal
2,Krude,Table,Metal,2,59,276.74,21.9,379.40,quick
3,Krude,Table,Glass,2,45,281.84,11.0,319.40,quick
4,Krude,Chair,Glass,9,35,69.74,3.2,120.21,slow

In [16]:
# After previewing, we shall remove the original delivery_days columN:
df = df.drop(columns=["delivery_days"])

In [18]:
# Let's inspect
df.head()

,brand,category,material,inventory,cost,discount_percentage,price,delivery_category
0,Furneyz,Bed,Plastic,105,181.61,27.8,273.18,slow
1,Krude,Chair,Glass,192,385.03,26.9,477.82,normal
2,Krude,Table,Metal,59,276.74,21.9,379.40,quick
3,Krude,Table,Glass,45,281.84,11.0,319.40,quick
4,Krude,Chair,Glass,35,69.74,3.2,120.21,slow